// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
// https://fernandorojo.co
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

const ChevronUpDown = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon" width="20" height="20" {...props}><Path stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M6.75 7.25 10 4l3.25 3.25M13.25 12.75 10 16l-3.25-3.25" /></Svg>;

export default ChevronUpDown;