// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
// https://fernandorojo.co
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

const Italic = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" width="20" height="20" {...props}><Path fillRule="evenodd" d="M8.05 2.75A.75.75 0 0 1 8.8 2h7.45a.75.75 0 0 1 0 1.5h-3.132l-4.643 13h2.785a.75.75 0 0 1 0 1.5H3.75a.75.75 0 0 1 0-1.5h3.132l4.643-13H8.8a.75.75 0 0 1-.75-.75Z" clipRule="evenodd" /></Svg>;

export default Italic;