// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
// https://fernandorojo.co
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

const Share = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" data-slot="icon" width="24" height="24" {...props}><Path fillRule="evenodd" d="M15.75 4.5a3 3 0 1 1 .825 2.066l-8.421 4.679a3.002 3.002 0 0 1 0 1.51l8.421 4.679a3 3 0 1 1-.729 1.31l-8.421-4.678a3 3 0 1 1 0-4.132l8.421-4.679a3 3 0 0 1-.096-.755Z" clipRule="evenodd" /></Svg>;

export default Share;