// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
// https://fernandorojo.co
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";

const Check = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" aria-hidden="true" data-slot="icon" width="24" height="24" {...props}><Path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" /></Svg>;

export default Check;