// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
// https://fernandorojo.co
export * as HeroSolid16 from './16/solid'
export * as HeroSolid20 from './20/solid'
export * as HeroOutline from './24/outline'
export * as HeroSolid from './24/solid'